### ISSUE TITLE
Virtio-Video driver for x86

### ISSUE THREAD

**Issue by FranzKafkaYu** [OpenSynergy/android-kernel-common#1]
Hello，Recently I have tried Android Trout as AAOS Virtual Device，and I need virtio-video driver for camera/video stream。And I have followed the official guide to compile Android Trout kernel for Virtio driver but failed in x86 version，could you plz give me some guide to compile this version for x86？

**Comment by FranzKafkaYu** [comment]
Hello developers，I have followed Android Official Instructions to compile virtio-video.ko for x86 and the kernel have loaded this driver，but when I launch trout_x86 instance ,there still no /dev/video* nodes for camera.So I'm wondering that whether this driver is compatiable with x86,can you help me?

**Comment by golubevmikhail** [comment]
Hi @FranzKafkaYu . To get to devfs nodes, the driver should detect a virtio video device. I am not sure, if the instructions you have followed do contain a hypervisor, that implements virtio video device. You can check virtio video device implementation in CrosVM, for example.

**Comment by FranzKafkaYu** [comment]
> Hi @FranzKafkaYu . To get to devfs nodes, the driver should detect a virtio video device. I am not sure, if the instructions you have followed do contain a hypervisor, that implements virtio video device. You can check virtio video device implementation in CrosVM, for example.

@golubevmikhail  Thanks for your reply! Actually I used Android Trout version which uses CrosVM as the underlying hypervisor.And I also found that the Virtio-video driver in CrosVM has been implemented(not sure whether it's fully usable).And Now when I connect camera by Chrome via webRTC, the Android camera2 Architecture can work and we can get the camera stream,but EVS can't work and I found there are no camera device nodes in /dev , did you have test Android Kernel with Virtio-Video driver for x86 system?
